dataset:
  directory: './dataset'  

model:
  input_channels: 8
  hidden_channels: 128
  output_channels: 56
  input_indices : [5, 12, 14, 21, 40, 49, 51, 58]
  name: cnn1

training:
  seed: 1
  batch_size: 16
  epoch: 50
  test_size : 0.1
  clip: 1.0
  inf: 1.0e+9
  beta: 0.5

optimizer:
  init_lr: 1.0e-3
  weight_decay: 1.0e-4
  adam_eps: 1.0e-8

lr_scheduler:
  factor: 0.9
  patience: 10
  warmup: 0